project:
  type: book
  output-dir: docs

book:
  title: "Promoting Accessibility in Duke Data Visualization"
  subtitle: "Creating a Color-Blind Friendly Duke Color Package"
  author: "Aidan Gildea"
  cover-image: images/dukelogo.png
  date: now
  abstract: "A detailed explanation of the development and use of the <b><i>duke</b></i> package."
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - functions.qmd
    - palmers.qmd
    - analysis.qmd
    - discussion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    mainfont: Atkinson-Hyperlegible
  pdf:
    documentclass: scrreprt

editor: visual

