# Discussion

The *duke* package allows users to transform their visualizations so that they are simultaneously colorblind friendly and representative of the Duke brand. To achieve this goal, the package incorporates a minimalist thematic design along with a high contrast color scale (both discrete and continuous) for ggplot geometric objects. As explained in the methods section, these functionalities are necessary and efficacious, but only a part of creators' toolbox for advancing accessibility in data visualization. There are several other best practices in data visualization that can make all the difference for those with color vision deficiency and low vision and should be highlighted. 

## Colorblind Accessibility Best Practices

**Keep It Simple**

The **duke** package selects a simple thematic design as to not distract from the key takeaways of the data visualization. It is in this vein that you should constantly consider how you can more succinctly convey the insights from your data. While the **duke** discrete palette allows for up to eight distinct colors, you should always strive to minimize the number of dimensions in your plots. Reducing the number of categories present in your visualizations is not only a best practice for colorblind accessibility. It also allows all users to more effectively differentiate between  distinctions in the data and quickly comprehend the primary takeaways. 

To reduce plot complexity, ask questions like: What do I need to highlight in the data? What are the primary insights readers should understand? This thought process will reveal what characteristics and/or categories must stand out and allow you to direct your attention on making them clear - especially for colorblind readers. Inversely, you can identify data groups that are insignificant to your goal and combine them into a single category, in turn, eliminating the need for excess colors. By keeping it simple in data visualization, you can be more confident that your audience will both comprehend and appreciate the story of your data visualization. 

**De-Emphasize the Need for Color**

The **duke** package allows users to integrate a more colorblind friendly palette into their visualizations; however, this is not the end-all solution. There are several other plot features present in **ggplot** that alleviate the need for the color palette to be perfectly distinguishable - or in some cases - be used at all. Essentially, if you "get it right in black and white", you no longer have to worry about access issues for colorblind readers [source](https://blog.datawrapper.de/colorblindness-part2/). This can be done by adding, "icons, directional arrows, labels, annotations, or other indicators" that differentiate between different categories [source](https://www.tableau.com/blog/examining-data-viz-rules-dont-use-red-green-together). 

Here are a few examples of how these supplementary features can improve the accessibility of visualizations using the **duke** package. 

Scatterplots can quickly become difficult to read when there a several distinct categories in the data. To improve your plot's readability, consider adding shapes to your data points.

[insert scatterplot with shapes] 

For geometric objects with large fill spaces (ie. bar plot, pie chart), the use of the colorblind friendly palettes can be effective on its own. Nevertheless, adding fill textures to your visualization is an effective way to increase plot clarity.

[insert bar plot with fill texture]

Finally, the efficacy of color in line plots deteriorates as the number of categories increases and/or the lines are intersecting. By varying the patterns and widths of the lines in your plot, your visualization can more effectively convey trend differences. 

[insert line plot with line patterns]

The use of these complimentary features - among many others - are easy and effective. By integrating them alongside the **duke** package, you can promote accessibility for not only colorblind individuals, but older readers, audiences with lower technical exposure, and people reading in low light. 


*Idea 3* Adjust when necessary. Some features of this package may not be perfect for you, so adapt them!
    - Text is scaled in package
        - work with it, if it does not appear appopriate use theme() to adjust so all texts feautures are sufficiently large
    - users can distinguish between lights vs. dark, even if they are similar colors [source](https://www.tableau.com/blog/examining-data-viz-rules-dont-use-red-green-together)
        - adjust the colors of this palette to be lighter/darker
        - if using a different palette, use the rule of light vs. dark if colors are not fully distinct
        
*Ideas if time*
    - monochromacy in viz --> by using different shades of same color, it can be more straightforward to users
    - interactive features 
        - hover effects the highlight data that belong to certain color/group
    - high dimensional data --> use glyphs
        - not a quick read but can express complicated info in understandable way
    