# Introduction

> Accessible design is good design -- it benefits people who don't have disabilities as well as people who do.
> Accessibility is all about removing barriers and providing the benefits for everyone.
>
> Steve Ballmer, former Microsoft CEO (2000-2014)

In nearly all disciplines, there is an increasing push to promote accessibility.
Data visualization should be no different.
The goal of this thesis is to detail the motivations, development, and use of the [**duke**](https://aidangildea.github.io/duke/) package.
By the end of "Promoting Accessibility in Duke Data Visualization," you should be sufficiently informed on how to create colorblind-friendly visualizations with colors that conform to Duke branding guidelines.

## Motivation

My interest in writing an undergraduate thesis is centered on two goals: 1) identifying a material issue and 2) addressing it with a tangible solution.
R packages tailored towards organization or company branding are quite common.
The [**ggtech**](https://github.com/ricardo-bion/ggtech) package allows users to incorporate colors representative of the Airbnb, Facebook, and Google brands, among many others, in their visualizations.
Users can also transform their visualizations to have aesthetic features aligned with The Economist and The Wall Street Journal brands via the [**ggthemes**](https://github.com/jrnold/ggthemes) package.
These are just a couple of examples of how an R package can auto-theme ggplot visualizations to meet the branding requirements of a company.
Only requiring a few functions, brand styling functions are easy-to-use yet very effective, making it an advantageous resource for companies to promote their brand.

With over 17,000 students, 38,000 employees, \$1 billion annually in research expenditures, and six campuses, Duke University's identity literally spans the globe [@dukeresearchinnovation].
And still, there exists no package to automate the process of making ggplot visualizations representative of the Duke brand.
It is an important need that has yet to be met and can only be in addressed via package development.
By learning the skill of package development to create a new Duke branding package, **duke**, I successfully meet my thesis criterion of 1) identifying a significant issue and 2) solving it with a real solution.

To best represent and communicate the Duke brand; however, the **duke** package must cater to the largest possible audience.
Thus, this project also centers on an important consideration in data visualization and branding package development: colorblind accessibility.
As our use of data increasingly permeates all aspects of society, it is crucial that we integrate accessibility and inclusivity into our data visualization best practices.
We must continuously consider questions like: Who is our audience?
How can we make our visualizations more intelligible?
Who might we be leaving behind?
This thesis aims to empower users right here in the Duke community to more easily answer these questions.
By developing an R package that allows for the creation of Duke official visualizations in a colorblind friendly way, we can begin to make accessibility a core tenet of data visualization.

## Background

There are approximately 300 million color blind people across the globe [@aboutcoa].
Approximately 1 in 12 men (8%) and 1 in 200 women (0.5%) are affected [@aboutcob].
More properly known as Color Vision Deficiency, or CVD, the condition is primarily inherited genetically but can also be acquired due to other chronic conditions such as diabetes.
With the data visualization industry expected to nearly double by 2026, its application will further become a mainstay in fields like marketing, research, public health, and journalism [@vissichelli2022].
More people will be interacting with data visualization than ever before -- both on the creator and reader ends -- therefore, it is crucial that it is increasingly accessible to those with CVD.

R packages that implement color blind friendly palettes already exist, but this project is unique in its aim to construct a package that makes Duke's color palette more accessible.
Duke provides a detailed description of its official [color suite](https://brand.duke.edu/colors/) and stresses its commitment to meeting the Web Content Accessibility Guidelines (WCAG).
The WCAG are globally recognized as the standard for web accessibility best practices in all fields [@initiative].
Duke details which color combinations from their suite are compliant, but does not offer a simple way to integrate the information into data visualizations.

The **duke** package intends to fill this need.
For Duke community members, the package will allow for easy integration of key aesthetic and geometric features that will make their visualizations clean, Duke branded, and accessible.
Given that the Statistics curriculum at Duke primarily uses [**ggplot2**](https://github.com/tidyverse/ggplot2) for visualization, **duke** will be focused on being compatible with its functionality.
By establishing a package that allows users to easily integrate Duke's style guide with color blind friendly adjustments, we can improve the accessibility of Duke related visualizations.
The implementation of this package will be an effective step toward accessibility in the Duke community, and hopefully, will prompt future work on making data visualization more inclusive.
