# Methods

## Color Sources

The office of University Communications provides an official color guide for the Duke brand. The color palette is intended to both bolster the brand of the University, as well as ensure cohesion among all official content \[1\]. The primary colors of the official palette are Duke Royal Blue and Duke Navy Blue. It is highly encouraged that one of these colors is present in any Duke official project, as they are reflective of the Duke Brand. The color guide also details an extended palette, which includes an additional 18 secondary and tertiary colors. Colors such as Copper, Eno, Ironweed, Persimmon, and Cast Iron are in the extended palette. University Communications urges the use of this extended palette for, "graphic accents, typography, backgrounds, \[and\] call-to-action buttons" \[2\]. For each color, users can access the following information:

-   Color Name

-   Pantone Matching System (PMS)

-   Hex Code (HEX)

-   Cyan, Magenta, Yellow, and Key (CMYK) Color Model

-   Red, Green, Blue Color Model

We will primarily use the Hex codes for these colors. Hex codes are a hexidecimal (base 16 numbering system) format for representing the amount of RBG in a particular shade \[3\] \[4\]. Additionally, hex codes are recognized as the best color system for HTML and CSS formats; therefore, their use will work well for data visualization in publication and web browser contexts.

| Color | Name            | Hex Code |
|-------|-----------------|----------|
|       | Duke Royal Blue | #00539B  |
|       | Duke Navy Blue  | #012169  |
|       | Copper          | #C84E00  |
|       | Persimmon       | #E89923  |
|       | Dandelion       | #FFD960  |
|       | Piedmont        | #A1B70D  |
|       | Eno             | #339898  |
|       | Magnolia        | #1D6363  |
|       | Prussian Blue   | #005587  |
|       | Shale Blue      | #0577B1  |
|       | Ironweed        | #993399  |
|       | Hatteras        | #E2E6ED  |
|       | Whisper Gray    | #F3F2F1  |
|       | Ginger Beer     | #FCF7E5  |
|       | Dogwood         | #988675  |
|       | Shackleford     | #DAD0C6  |
|       | Cast Iron       | #262626  |
|       | Graphite        | #666666  |
|       | Granite         | #B5B5B5  |
|       | Limestone       | #E5E5E5  |

: **Duke Color Palette**

In 2018, a color accessibility guide was added to the brand guide outlining how users could meet Web Content Accessibility Guidelines (WCAG) 2.0 AA guidelines. The WCAG are internationally recognized standards on how to make web content more accessible to people with disability - including those with color vision deficiency. Their accessibility standards are principled on four tenets: Perceivable, Operable, Understandable, and Robust \[5\]. Duke's accessibility guide illustrates a grid of every text-background color pairing and its respective compliance to the WCAG. There are four compliance categories specified:

-   AAA: highest compliance, text-background contrast ratio of 7+

-   AA: mid-range compliance, text-background contrast ratio of 4.5+

-   AA18: mid-range compliance with large text only (18pt or 14pt bold), text-background contrast ratio of 3+

-   DNP: does not pass compliance guidelines, text-background contrast ratio of less than 3

These compliance metrics are an important resource for identifying color combinations that are inaccessible and eliminating them from use in the ***duke*** package. The ratios provided by this guideline are intended for background and foreground combinations; however, also apply to colors near and/ore adjacent to one another. Duke's inclusion of an accessibility guide on their branding website is an important step, but it would benefit from a built-in functionality that allows users to interact with its information more easily. The ***duke*** package aims to empower users to engage with these accessibility recommendations more easily when creating data visualizations.

-   Outline Process for Color Selection

    -   Weighing metrics like color distance

    -   Integrating multiple color palettes into the package

        -   Balance of aesthetic (particularly with regard to Duke) as well as accessibility

## Package Development

As previously mentioned, package development posed a new challenge to the skill set I had learned through the Statistics curriculum. The "R Packages" text book served as an essential guide for learning, understanding, and eventually building the ***duke*** package. By clearly outlining the key structures of an R package, the functionality of the devtools package, and the importance of testing, I was well equipped to create ***duke***.

The ***duke*** package offers four functions for users to make Duke branded visualizations in a colorblind friendly way.

### theme_duke()

This function is largely inspired by the `theme()` function and its many derivatives. Its primary focus is the set the aesthetic elements for the the visualization's background and accessory features. These include the background color, grid lines, axis ticks, plot text, etc. With accessibility at the forefront of this project's goals, it is essential that these choices lead to not only a visually pleasing result, but one that is intellgible as well. To do so, `theme_duke()` implements a minimalist design with a white background and grid lines removed. This is to ensure that audiences can focus on the story the data tells, rather than be confused by excessive theming. This design is complemented by uniform font text and coloring across the entirety of the visualization. Titles, axes, captions, and more, are all in Duke Navy Blue because of its strong contrast from the white background. It has a contrast ratio of 14.76 with white, which is the third highest among all colors in the Duke extended palette.

In addition, all text is in Atkinson-Hyperlegible font. ####Created by blah, intended for blah, it is essential to ensuring accessibility in this package. Font implementation was one of the most difficult challenges throughout the package development process. RStudio provides a limited suite of fonts, requiring users to download and load additional font families to their own system. On the individual-level, this is not too difficult. However, the process necessitates careful thought when building a package for community use. *How can users integrate quickly access the package's required fonts? What font implementation will require minimal memory? Why is being transparent with users important?* The list goes on and that is why adding font specification to ***duke*** required considerable thought.

\*\* Explain font implementation, as well as what happens when users don't have text

### scale_duke_continuous()

### scale_duke_color_discrete

### scale_duke_fill_discrete

    -   Starting with the dummy regexcite package to better understand package creation

    -   Creating first function

        -   practicing formatting, devtools function use, and implementation with graph

    -   Applying those lessons to all other functions

    -   Importance of creating test cases (testthat files)

        -   Use of cover package

    -   Lessons learned through the process

        -   iterative process --\> identify issues immediately and address them

        -   engage with existing resources/packages

            -   drew a lot from other theme/scale_color functionalities

## References

    1.  https://brand.duke.edu/colors/
    2.  Ibid
    3.  https://www.techopedia.com/definition/29788/color-hex-code
    4.  https://www.sciencedirect.com/topics/engineering/hexadecimal
    5.  https://www.w3.org/TR/UNDERSTANDING-WCAG20/intro.html#introduction-fourprincs-head
